In [1]:
import xarray as xr
import numpy as np
import sys
sys.path.append('/home/563/rl5183/PhD-research/Functions')
import functions as func
from importlib import reload

In [2]:
#read in obs and detrend 
ersst_ds = xr.open_dataset('/g/data/eg3/jxb548/OBSDATA/ersstv5.1950_2018.nc')
ersst_sst = ersst_ds.sst
#detrend
ersst_detrend = np.apply_along_axis(func.detrend_2step, 0, ersst_sst)
ersst_sst_dt = xr.DataArray(ersst_detrend, coords=ersst_sst.coords, attrs=ersst_sst.attrs)

In [3]:
#calculate nino34 index
nino34_index =  func.nino34_index(ersst_sst_dt, '1950-01', '1979-12')

In [5]:
#calculate el nino and la nina years using the DJF nino34 index
yearly_seasonal_nino34_index = func.seasonal_mean_nino_index(nino34_index)
yearly_seasonal_nino34_index_djf = yearly_seasonal_nino34_index.sel(season='DJF').drop_sel(seasonyear=2019)
el_nino_years_djf = yearly_seasonal_nino34_index_djf.where(yearly_seasonal_nino34_index_djf>0.4, drop=True).seasonyear
la_nina_years_djf = yearly_seasonal_nino34_index_djf.where(yearly_seasonal_nino34_index_djf<-0.4, drop=True).seasonyear
el_nino_years_djf = el_nino_years_djf -1
la_nina_years_djf = la_nina_years_djf -1

In [7]:
#calculate el nino and la nina years using 6-month nino34 index
el_nino_years_six_month, la_nina_years_six_month = func.nino_years(nino34_index, 0.4, 6)

In [14]:
el_nino_years_six_month

<xarray.DataArray 'year' (time: 20)>
array([1951, 1953, 1957, 1963, 1965, 1968, 1972, 1976, 1977, 1982, 1986,
       1991, 1993, 1994, 1997, 2002, 2004, 2006, 2009, 2014])
Coordinates:
  * time        (time) datetime64[ns] 1951-07-01 1953-04-01 ... 2014-12-01
    month       (time) int64 7 4 5 7 7 10 7 10 10 6 10 5 5 7 7 7 8 10 9 12
    seasonyear  (time) int64 1951 1953 1957 1963 1965 ... 2004 2006 2009 2015

In [15]:
el_nino_years_djf

<xarray.DataArray 'seasonyear' (seasonyear: 26)>
array([1951, 1953, 1957, 1958, 1963, 1965, 1968, 1969, 1972, 1976, 1977,
       1979, 1982, 1986, 1987, 1990, 1991, 1994, 1997, 2002, 2003, 2004,
       2006, 2009, 2014, 2015])
Coordinates:
    season      <U3 'DJF'
  * seasonyear  (seasonyear) int64 1952 1954 1958 1959 ... 2007 2010 2015 2016

In [10]:
la_nina_years_six_month

<xarray.DataArray 'year' (time: 13)>
array([1950, 1954, 1964, 1970, 1973, 1984, 1988, 1995, 1998, 2007, 2010,
       2016, 2017])
Coordinates:
  * time        (time) datetime64[ns] 1950-05-01 1954-08-01 ... 2017-12-01
    month       (time) int64 5 8 7 9 7 12 7 11 9 9 8 10 12
    seasonyear  (time) int64 1950 1954 1964 1970 1973 ... 2007 2010 2016 2018

In [11]:
la_nina_years_djf

<xarray.DataArray 'seasonyear' (seasonyear: 25)>
array([1950, 1954, 1955, 1956, 1962, 1964, 1970, 1971, 1973, 1974, 1975,
       1983, 1984, 1988, 1995, 1998, 1999, 2000, 2005, 2007, 2008, 2010,
       2011, 2016, 2017])
Coordinates:
    season      <U3 'DJF'
  * seasonyear  (seasonyear) int64 1951 1955 1956 1957 ... 2011 2012 2017 2018